name: DEKAP_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - gurobi
dependencies:
  - anyio=4.2.0
  - argon2-cffi-bindings=21.2.0
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates
  - certifi
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gmpy2=2.1.2
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema-specifications=2023.7.1
  - jsonschema=4.19.2
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libclang=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libnpp-dev=12.2.5.2
  - libnpp=12.2.5.2
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base
  - matplotlib-inline=0.1.6
  - matplotlib
  - mistune=2.0.4
  - mkl-service=2.4.0
  - mkl=2023.1.0
  - mkl_fft
  - mkl_random
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook-shim=0.2.3
  - numba
  - numexpr
  - numpy-base=1.23.5
  - numpy
  - openjpeg=2.5.2
  - openssl
  - overrides=7.4.0
  - packaging=24.1
  - pandas
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycparser=2.21
  - pygments=2.15.1
  - pynndescent
  - pyparsing=3.0.9
  - pyqt5-sip=12.13.0
  - pyqt=5.15.10
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python=3.10.14
  - pytorch-cuda
  - pytorch=2.4.1
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn
  - scipy
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.13.2
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - tzdata=2024a
  - umap-learn
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - visdom
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - libarchive
  - tensorboard
  - seaborn
  - kagglehub
  - pytorch-lightning
  - gdown
  - gurobi
  - pip:
    - about-time==4.2.1
    - alive-progress==3.2.0
    - annotated-types==0.7.0
    - astunparse==1.6.3
    - autograd==1.7.0
    - cachetools==5.5.0
    - clarabel==0.10.0
    - click==8.2.1
    - cloudpickle==3.1.1
    - cma==3.2.2
    - cssselect==1.2.0
    - cssutils==2.11.1
    - cvxpy==1.6.3
    - cython==3.0.12
    - deprecated==1.2.18
    - dill==0.3.9
    - fire==0.7.0
    - flatbuffers==24.12.23
    - fsspec==2024.9.0
    - gast==0.6.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-pasta==0.2.0
    - grapheme==0.6.0
    - h5py==3.12.1
    - ipywidgets==8.1.5
    - jupyterlab-widgets==3.0.13
    - keras==3.7.0
    - libclang==18.1.1
    - lxml==5.3.0
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - ml-dtypes==0.4.1
    - more-itertools==10.5.0
    - namex==0.0.8
    - numpy==1.24.3
    - nvidia-ml-py==12.575.51
    - nvitop==1.5.1
    - opt-einsum==3.4.0
    - optree==0.13.1
    - osqp==0.6.7.post3
    - patsy==1.0.1
    - premailer==3.10.0
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pygad==3.4.0
    - pymoo==0.6.1.3
    - pyscipopt==5.4.1
    - qdldl==0.1.7.post5
    - rich==13.9.4
    - scs==3.2.7.post2
    - sentry-sdk==2.32.0
    - smmap==5.0.2
    - statsmodels==0.14.4
    - tensorboard==2.18.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.5.0
    - torchaudio==2.4.1
    - torchvision==0.19.1
    - typing-extensions==4.14.1
    - typing-inspection==0.4.1
    - wandb==0.21.0
    - widgetsnbextension==4.0.13
    - wrapt==1.17.0
    - yagmail==0.15.293
